(function () {
  const dronePrompt = "Preserve the exact architecture, proportions, materials, openings, landscape and layout. Create a cinematic architectural drone tour with smooth aerial camera movement, luxury real estate style, realistic daylight, no distortion, no invented buildings.";
  const constructionPrompt = "Create a cinematic construction transformation from raw unfinished grey shell to final premium architectural interior. Preserve the exact layout and geometry. Show progressive construction stages, realistic materials, no cartoon look, no impossible transformations.";
  const decorationPrompt = "Transform an empty architectural interior into a fully decorated premium space step by step. Preserve the exact room geometry, windows, walls, floor, ceiling and camera composition. Add furniture and decoration progressively, realistic materials, sophisticated interior design.";
  const frontAerialPrompt = "Create a smooth camera transition from frontal architectural view to aerial view. Preserve exact building design, facade, materials, proportions and context. Realistic drone/crane camera movement, no distortion, no new buildings.";
  const orbitPrompt = "Create a simple 360-style orbit around the architectural subject. Preserve the exact design, scale, proportions, materials and object placement. Smooth camera orbit, realistic lighting, no warped geometry.";
  const walkthroughPrompt = "Generate a cinematic architectural walkthrough. Smooth dolly forward movement, premium real estate style, preserve exact layout, materials, furniture, lighting and proportions. No object deformation, no extra rooms, no fantasy elements.";
  const cadPrompt = "Transform an architectural floor plan or technical drawing into a realistic architectural visualization. Respect the original plan layout, walls, openings, proportions and spatial organization. Show a cinematic transition from blueprint/CAD style to photorealistic render.";

  function output(id, stageName, description, basePrompt, editInstructions, negativePrompt, mustShow = [], mustNotShow = []) {
    return {
      id,
      stageName,
      description,
      basePrompt,
      editInstructions,
      mustShow: mustShow.length ? mustShow : [description, stageName].filter(Boolean),
      mustNotShow: mustNotShow.length ? mustNotShow : ["major architectural changes", "layout changes", "camera drift"],
      negativePrompt,
    };
  }

  window.VIDEO_TEMPLATES = [
    {
      id: "drone-tour",
      name: "Tour de dron",
      description: "Video extenso y cinematografico que simula un recorrido de dron sobre o alrededor del proyecto arquitectonico.",
      category: "real_estate",
      defaultDurationSeconds: 10,
      minDurationSeconds: 5,
      maxDurationSeconds: 30,
      defaultAspectRatio: "16:9",
      requiredInputs: ["image", "render", "reference"],
      supportsHumans: true,
      supportsCars: true,
      defaultCameraMotion: "slow aerial drone reveal",
      internalPromptStrategy: "Generate front, diagonal, context, low aerial and final aerial hero views.",
      lumaPromptTemplate: dronePrompt,
      imagePromptCount: 5,
      baseImageOutputs: [
        output("front-hero", "Vista frontal hero", "Fachada o escena principal en vista frontal clara.", dronePrompt, "Preserve facade, proportions, signage, openings and immediate context. Improve realism and photographic daylight only.", "No geometry changes, no invented buildings, no distorted facade."),
        output("diagonal-perspective", "Vista diagonal/perspectiva", "Vista oblicua que revela profundidad y volumen.", dronePrompt, "Keep the same architectural identity while creating a plausible diagonal/perspective interpretation from the reference. Do not redesign materials or openings.", "No warped geometry, no new massing, no extra buildings."),
        output("side-context", "Vista lateral o contexto", "Vista con contexto lateral, acceso, calle, jardin o entorno inmediato.", dronePrompt, "Show a side/context stage only if plausible from the reference. Preserve landscape intent and do not invent unrelated surroundings.", "No fantasy landscape, no traffic unless cars are enabled."),
        output("low-aerial", "Vista aerea baja", "Camara elevada suave para preparar el movimiento de dron.", dronePrompt, "Create a low aerial view that respects the original footprint, rooflines and proportions.", "No roof distortion, no new neighboring buildings."),
        output("final-aerial", "Vista aerea final", "Cierre cinematografico desde altura controlada.", dronePrompt, "Create a final semi-aerial hero view, luxury real estate style, with the same project identity and layout.", "No invented context, no scale drift, no exaggerated drone angle."),
      ],
    },
    {
      id: "grey-shell-construction",
      name: "Construccion desde obra gris",
      description: "Muestra evolucion desde obra gris hasta estado final.",
      category: "construction",
      defaultDurationSeconds: 12,
      minDurationSeconds: 5,
      maxDurationSeconds: 30,
      defaultAspectRatio: "16:9",
      requiredInputs: ["image", "plan", "reference"],
      supportsHumans: true,
      supportsCars: false,
      defaultCameraMotion: "locked cinematic transformation",
      internalPromptStrategy: "Generate raw shell, clean structure, initial finishes, progressive fit-out and final photoreal result.",
      lumaPromptTemplate: constructionPrompt,
      imagePromptCount: 5,
      baseImageOutputs: [
        output("raw-shell", "Obra gris inicial", "Version del espacio en estado inicial de obra gris, sin acabados finales.", "Create a photorealistic raw grey-shell construction stage of the same architectural space.", "Remove final furniture and decoration only for this construction-stage version. Preserve exact geometry, camera angle, openings, wall positions, ceiling, floor layout and spatial proportions. Show unfinished concrete or plaster surfaces, raw floor, visible construction state, but do not change architecture.", "No finished furniture, no luxury decoration, no people unless requested, no cars unless requested, no geometry changes."),
        output("base-structure", "Estructura limpia", "Espacio con estructura base limpia y primeros elementos constructivos.", "Create a photorealistic early construction progress stage of the same architectural space.", "Preserve all architecture and composition. Add clean base walls, early floor preparation and construction-ready surfaces. Do not add final furniture yet. Do not modify layout.", "No finished decoration, no layout changes, no invented rooms."),
        output("initial-finishes", "Acabados iniciales", "Primeros acabados visibles: piso, paredes, iluminacion o materiales base.", "Create a photorealistic mid-construction stage where the initial finishes are being installed.", "Preserve geometry and original design intent. Show floors, wall finishes and lighting beginning to appear. Keep the exact space identity and proportions.", "No excessive decoration, no geometry changes, no unrealistic construction."),
        output("decor-progress", "Decoracion/mobiliario progresivo", "El espacio empieza a recibir mobiliario, detalles y decoracion.", "Create a photorealistic advanced fit-out stage of the same space.", "Preserve layout, camera and design identity. Add furniture and decorative elements progressively only according to the original/final design reference. Do not invent a new style.", "No unrelated furniture, no design changes, no extra rooms."),
        output("final-result", "Resultado final", "Imagen final hiperrealista del diseno terminado.", "Create a final ultra-photorealistic render of the completed architectural space.", "Preserve the exact final design, materials, furniture positions, signage, layout, camera angle and composition. Improve only realism, lighting, textures, photographic quality and material accuracy.", "No design changes, no object relocation, no added objects unless requested."),
      ],
    },
    {
      id: "progressive-decoration",
      name: "Decoracion progresiva",
      description: "Empieza con espacio vacio y muestra decoracion progresiva.",
      category: "interior",
      defaultDurationSeconds: 10,
      minDurationSeconds: 5,
      maxDurationSeconds: 30,
      defaultAspectRatio: "16:9",
      requiredInputs: ["image", "reference"],
      supportsHumans: true,
      supportsCars: false,
      defaultCameraMotion: "slow interior reveal",
      internalPromptStrategy: "Generate empty space, initial furniture, materials and lighting, advanced decoration and final interior.",
      lumaPromptTemplate: decorationPrompt,
      imagePromptCount: 5,
      baseImageOutputs: [
        output(
          "empty-space",
          "Espacio vacio",
          "Mostrar el espacio limpio, sin decoracion ni mobiliario final.",
          "Create a photorealistic rendered version of the same interior space completely empty, without decoration, without styled furniture, preserving the exact room geometry, walls, windows, doors, floor proportions and camera angle.",
          "Remove decorative objects, remove final styling, remove most movable furniture unless some fixed architectural furniture must remain. Show a clean, realistic, undecorated room with architectural fidelity.",
          "Do not change architecture. Do not add final decor. Do not invent new furniture layout. Do not alter room proportions.",
          ["same room geometry", "same camera angle", "same walls, doors and openings", "realistic empty interior"],
          ["final decoration", "styled accessories", "fully dressed bed if that belongs to final styling", "decorative art or final ambiance props"],
        ),
        output(
          "initial-furniture",
          "Mobiliario inicial",
          "Introducir mobiliario grande y principal, pero sin decoracion final completa.",
          "Create a photorealistic rendered version of the same room with initial primary furniture placement only.",
          "Preserve architecture and composition. Add the main large furniture pieces such as bed, chair, table, sofa or essential furniture in a simple early staged form, but keep the space minimally decorated.",
          "Do not fully decorate the scene. Do not add final styling layers. Do not change design layout.",
          ["main furniture pieces", "same room composition", "same geometry"],
          ["full decorative styling", "all accessories", "fully finished ambiance"],
        ),
        output(
          "materials-lighting",
          "Materiales e iluminacion",
          "El espacio ya tiene mobiliario principal y empieza a sentirse disenado por materiales, textiles e iluminacion.",
          "Create a photorealistic rendered version of the same room where materials, lighting mood and core finishes are now established.",
          "Preserve room architecture and furniture placement. Introduce stronger material identity, textiles, lighting quality, tonal harmony and partial decor, but do not yet show the fully finished styled result.",
          "Do not over-style the scene. Do not make it look fully final yet. Do not change architecture.",
          ["main furniture", "clear material identity", "lighting ambiance", "partial decor"],
          ["maximum decoration density", "all final accessories"],
        ),
        output(
          "advanced-decor",
          "Decoracion avanzada",
          "El espacio se ve muy avanzado, casi final, con decoracion importante ya aplicada.",
          "Create a photorealistic rendered version of the same room with advanced decoration and refined interior styling.",
          "Preserve exact architecture and composition. Show the space nearly complete, with layered decor, accessories and styling, but still as the step before the final hero image.",
          "Do not alter room proportions. Do not invent new architecture. Do not change camera.",
          ["rich styling", "decorative accessories", "strong mood", "nearly complete design"],
          ["major architectural changes", "layout changes"],
        ),
        output(
          "final-result",
          "Resultado final",
          "Imagen hero final hiperrealista del espacio terminado.",
          "Create the final ultra-photorealistic hero render of the completed space.",
          "Preserve the exact design intent, architecture, layout, camera angle and furniture composition. Show the complete final decorated and polished result with maximum realism.",
          "Do not change the design. Do not alter architecture. Do not move objects unnecessarily.",
          ["full decoration", "full realism", "complete styling", "final atmosphere"],
          ["design changes", "architecture changes", "unnecessary object relocation"],
        ),
      ],
    },
    {
      id: "front-to-aerial",
      name: "Vista frontal a vista aerea",
      description: "Empieza en vista frontal y termina en vista aerea o semi-aerea.",
      category: "architecture",
      defaultDurationSeconds: 8,
      minDurationSeconds: 5,
      maxDurationSeconds: 30,
      defaultAspectRatio: "16:9",
      requiredInputs: ["image", "render"],
      supportsHumans: true,
      supportsCars: true,
      defaultCameraMotion: "vertical crane / drone rise",
      internalPromptStrategy: "Generate frontal, elevated frontal, elevated diagonal and soft aerial views.",
      lumaPromptTemplate: frontAerialPrompt,
      imagePromptCount: 4,
      baseImageOutputs: [
        output("front-view", "Vista frontal", "Vista frontal fiel y clara.", frontAerialPrompt, "Preserve the original front view, facade, openings, materials, signage and context. Improve realism only.", "No perspective drift, no new facade design."),
        output("elevated-front", "Vista frontal elevada", "Misma fachada con camara levemente mas alta.", frontAerialPrompt, "Raise the camera subtly while preserving facade geometry and proportions.", "No roof distortion, no new floors, no invented massing."),
        output("elevated-diagonal", "Vista diagonal elevada", "Transicion hacia angulo diagonal alto.", frontAerialPrompt, "Create a plausible elevated diagonal view that keeps the exact building identity and material intent.", "No new buildings, no scale drift, no warped openings."),
        output("soft-aerial", "Vista aerea suave", "Cierre semi-aereo sobrio.", frontAerialPrompt, "Create a soft aerial view with realistic drone/crane motion, preserving footprint and context.", "No impossible camera, no redesigned roof, no invented context."),
      ],
    },
    {
      id: "simple-360",
      name: "Vista 360 sencilla",
      description: "Simula una rotacion alrededor del objeto, fachada o espacio.",
      category: "architecture",
      defaultDurationSeconds: 8,
      minDurationSeconds: 5,
      maxDurationSeconds: 9,
      defaultAspectRatio: "16:9",
      requiredInputs: ["image", "render"],
      supportsHumans: false,
      supportsCars: true,
      defaultCameraMotion: "subtle orbit",
      internalPromptStrategy: "Generate front, left diagonal, side, right diagonal and final front views.",
      lumaPromptTemplate: orbitPrompt,
      imagePromptCount: 5,
      baseImageOutputs: [
        output("front", "Frente", "Vista frontal inicial.", orbitPrompt, "Preserve the exact front composition, scale, materials and object placement.", "No geometry drift, no new objects."),
        output("left-diagonal", "Diagonal izquierda", "Rotacion leve hacia izquierda.", orbitPrompt, "Create a left diagonal angle while maintaining the same design, proportions and material identity.", "No warped geometry, no changed scale."),
        output("side", "Lateral", "Vista lateral controlada.", orbitPrompt, "Create a side view only as a plausible orbit stage. Preserve project identity and object positions.", "No invented side features, no new rooms."),
        output("right-diagonal", "Diagonal derecha", "Rotacion leve hacia derecha.", orbitPrompt, "Create a right diagonal angle with consistent design and scale.", "No design changes, no distorted facade."),
        output("front-final", "Frente final", "Vuelta al frente con acabado hero.", orbitPrompt, "Return to a polished front hero view with realistic lighting and exact identity.", "No changed signage, no added elements unless requested."),
      ],
    },
    {
      id: "architectural-walkthrough",
      name: "Recorrido arquitectonico",
      description: "Un recorrido interior o exterior tipo walkthrough.",
      category: "architecture",
      defaultDurationSeconds: 10,
      minDurationSeconds: 5,
      maxDurationSeconds: 30,
      defaultAspectRatio: "16:9",
      requiredInputs: ["image", "render", "reference"],
      supportsHumans: true,
      supportsCars: true,
      defaultCameraMotion: "slow dolly forward",
      internalPromptStrategy: "Generate entrance, midpoint, main area, architectural detail and hero closing views.",
      lumaPromptTemplate: walkthroughPrompt,
      imagePromptCount: 5,
      baseImageOutputs: [
        output("entrance", "Entrada", "Inicio del recorrido.", walkthroughPrompt, "Show the entrance or first viewpoint while preserving the original layout, camera direction and material intent.", "No extra rooms, no changed openings."),
        output("midpoint", "Punto medio", "Avance suave hacia el espacio principal.", walkthroughPrompt, "Create a midpoint stage for a dolly-forward walkthrough. Keep geometry and furniture positions consistent.", "No object deformation, no fantasy elements."),
        output("main-area", "Area principal", "Momento central del recorrido.", walkthroughPrompt, "Reveal the main architectural area with premium real estate lighting and exact design fidelity.", "No layout changes, no invented furniture."),
        output("detail", "Detalle arquitectonico", "Enfoque en textura, material o pieza clave.", walkthroughPrompt, "Emphasize an architectural detail while preserving original materials, signage and object placement.", "No unrelated closeup, no new materials."),
        output("hero-closing", "Cierre hero", "Imagen final cinematografica.", walkthroughPrompt, "Create a final hero closing view, polished and photorealistic, without changing the project identity.", "No extra rooms, no design drift, no people unless requested."),
      ],
    },
    {
      id: "cad-to-realistic",
      name: "De planos AutoCAD a realista",
      description: "Convierte planos o referencias tecnicas en narrativa visual que termina en render realista.",
      category: "technical",
      defaultDurationSeconds: 12,
      minDurationSeconds: 5,
      maxDurationSeconds: 30,
      defaultAspectRatio: "16:9",
      requiredInputs: ["dxf", "dwg", "pdf", "plan"],
      supportsHumans: false,
      supportsCars: false,
      defaultCameraMotion: "technical-to-realistic reveal",
      internalPromptStrategy: "Generate technical plan, highlighted plan, basic volume, semi-realistic space and final photoreal render.",
      lumaPromptTemplate: cadPrompt,
      imagePromptCount: 5,
      baseImageOutputs: [
        output("technical-plan", "Plano tecnico limpio", "Plano o dibujo tecnico legible.", cadPrompt, "Clean and clarify the technical drawing while respecting wall layout, openings, proportions and labels.", "No changed plan, no invented rooms."),
        output("highlighted-plan", "Plano resaltado", "Plano con zonas destacadas para lectura narrativa.", cadPrompt, "Highlight important zones or circulation without changing the underlying plan.", "No altered walls, no wrong labels."),
        output("basic-volume", "Volumen basico", "Transicion a volumen arquitectonico simple.", cadPrompt, "Translate the plan into a basic massing/volume while respecting spatial organization and proportions.", "No invented geometry, no impossible volumes."),
        output("semi-realistic", "Visualizacion semirrealista", "Primera visualizacion con materiales y profundidad.", cadPrompt, "Develop a semi-realistic visualization from the plan, keeping walls, openings and layout faithful.", "No extra rooms, no changed proportions."),
        output("final-render", "Render final", "Resultado hiperrealista basado en el plano.", cadPrompt, "Create the final photorealistic render from the technical reference. Preserve floor plan, openings, proportions and spatial organization.", "No plan changes, no invented architecture, no humans or cars unless explicitly requested."),
      ],
    },
  ];
})();
