(function () {
  const DEFAULT_INSPECTOR_SECTIONS = [
    "readiness",
    "analysis",
    "visualInventory",
    "stagePrompts",
    "clipPrompts",
    "fidelityRules",
    "warnings",
  ];

  function createVideoTemplate(config) {
    return {
      id: config.id,
      name: config.name,
      shortName: config.shortName || config.name,
      description: config.description || "",
      category: config.category || "architecture",
      purpose: config.purpose || config.description || "",
      bestFor: config.bestFor || [],
      notFor: config.notFor || [],
      requiredInputs: config.requiredInputs || ["image", "render", "reference"],
      optionalInputs: config.optionalInputs || [],
      minimumRecommendedInputs: Number(config.minimumRecommendedInputs || 1),
      singleImagePolicy: config.singleImagePolicy || "allowed_with_caution",
      defaultDurationSeconds: Number(config.defaultDurationSeconds || 10),
      minDurationSeconds: Number(config.minDurationSeconds || 5),
      maxDurationSeconds: Number(config.maxDurationSeconds || 30),
      defaultAspectRatio: config.defaultAspectRatio || "16:9",
      supportsHumans: Boolean(config.supportsHumans),
      supportsCars: Boolean(config.supportsCars),
      defaultCameraMotion: config.defaultCameraMotion || "slow cinematic architectural movement",
      analysisFocus: config.analysisFocus || [],
      readinessChecks: config.readinessChecks || [],
      baseImageOutputs: (config.baseImageOutputs || []).map(createBaseImageOutput),
      clipStrategy: {
        defaultClipDurationSeconds: 5,
        motionStyle: "stable, smooth, cinematic, architecture-preserving",
        sequencing: "one clip per approved base image",
        ...config.clipStrategy,
      },
      finalCompositionStrategy: config.finalCompositionStrategy || "Compose approved clips in stage order with clean cuts or soft cross dissolves.",
      inspectorSections: config.inspectorSections || DEFAULT_INSPECTOR_SECTIONS,
      forbiddenChanges: config.forbiddenChanges || [
        "geometry",
        "layout",
        "camera composition",
        "main materials",
        "doors",
        "windows",
        "visible text",
      ],
      templateWarnings: config.templateWarnings || [],
      imagePromptCount: (config.baseImageOutputs || []).length,
      internalPromptStrategy: config.internalPromptStrategy || config.purpose || "",
      lumaPromptTemplate: config.lumaPromptTemplate || config.defaultCameraMotion || "",
    };
  }

  function createBaseImageOutput(config) {
    const id = config.id || String(config.stageName || "stage").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
    return {
      id,
      stageName: config.stageName || "Stage",
      stageNumber: Number(config.stageNumber || 1),
      description: config.description || "",
      stagePurpose: config.stagePurpose || config.description || "",
      analysisNeeded: config.analysisNeeded || [],
      mustKeep: config.mustKeep || [],
      mayRemove: config.mayRemove || [],
      mayAdd: config.mayAdd || [],
      mustShow: config.mustShow || [],
      mustNotShow: config.mustNotShow || [],
      inventoryMapping: config.inventoryMapping || {
        useArchitecture: true,
        useLargeObjects: true,
        useMediumObjects: true,
        useSmallObjects: true,
        useMaterials: true,
        useLighting: true,
        useVisibleText: true,
        useCamera: true,
      },
      basePrompt: config.basePrompt || "",
      editInstructions: config.editInstructions || "",
      stageDeltaInstructions: config.stageDeltaInstructions || "",
      negativePrompt: config.negativePrompt || "No geometry changes, no layout changes, no camera drift, no distorted architecture, no invented rooms, no warped text.",
      motionPrompt: config.motionPrompt || "",
      clipMotion: {
        cameraMove: config.clipMotion?.cameraMove || config.motionPrompt || "slow stable push-in",
        speed: config.clipMotion?.speed || "slow",
        transitionIn: config.clipMotion?.transitionIn || "soft cut",
        transitionOut: config.clipMotion?.transitionOut || "cross dissolve",
        stabilityRules: config.clipMotion?.stabilityRules || [
          "Preserve exact architecture.",
          "No morphing.",
          "No object identity changes.",
          "No added or removed elements unless explicitly requested.",
        ],
      },
    };
  }

  function stage(id, stageNumber, stageName, stagePurpose, options) {
    return createBaseImageOutput({
      id,
      stageNumber,
      stageName,
      description: stagePurpose,
      stagePurpose,
      analysisNeeded: options.analysisNeeded || ["architecture", "camera", "materials", "objects", "visible text"],
      mustKeep: options.mustKeep || ["geometry", "layout", "camera composition", "architectural identity"],
      mayRemove: options.mayRemove || [],
      mayAdd: options.mayAdd || [],
      mustShow: options.mustShow || [],
      mustNotShow: options.mustNotShow || ["new architecture", "changed layout", "warped perspective"],
      basePrompt: options.basePrompt,
      editInstructions: options.editInstructions,
      stageDeltaInstructions: options.stageDeltaInstructions,
      negativePrompt: options.negativePrompt,
      motionPrompt: options.motionPrompt,
      clipMotion: options.clipMotion,
      inventoryMapping: options.inventoryMapping,
    });
  }

  const fidelityForbidden = [
    "change geometry",
    "change layout",
    "change camera",
    "invent architecture",
    "move doors or windows",
    "change visible text",
    "alter structural proportions",
  ];

  const templates = [
    createVideoTemplate({
      id: "drone-tour",
      name: "Tour de dron exterior",
      shortName: "Dron exterior",
      description: "Video inmobiliario exterior con movimiento de dron alrededor o sobre el proyecto.",
      category: "exterior",
      purpose: "Crear video inmobiliario exterior con movimiento de dron alrededor o sobre el proyecto.",
      bestFor: ["casas", "fachadas", "locales comerciales exteriores", "hoteles", "edificios bajos", "contexto exterior"],
      notFor: ["interiores", "habitaciones", "espacios sin fachada visible"],
      requiredInputs: ["image", "render", "reference"],
      optionalInputs: ["plan", "site_photo"],
      minimumRecommendedInputs: 1,
      singleImagePolicy: "allowed_exterior_only",
      defaultDurationSeconds: 10,
      supportsHumans: true,
      supportsCars: true,
      defaultCameraMotion: "slow aerial drone reveal",
      analysisFocus: ["facade", "roof", "street", "parking", "garden", "signage", "exterior context"],
      readinessChecks: ["block if dominant analysis is interior", "warn if roof is not visible"],
      baseImageOutputs: [
        stage("front-hero", 1, "Vista frontal hero", "Presentar fachada principal.", {
          mustKeep: ["facade", "proportions", "doors", "windows", "signage", "materials", "access"],
          mayAdd: ["realism", "natural sky", "improved existing vegetation"],
          mustNotShow: ["invented buildings", "changed facade", "changed signage"],
          basePrompt: "Create a front hero exterior architectural view, photorealistic and luxury real estate ready.",
          editInstructions: "Preserve facade, proportions, access, openings, materials and signage exactly.",
          stageDeltaInstructions: "Improve realism, daylight, sky and material clarity only.",
          motionPrompt: "slow frontal push-in",
          clipMotion: { cameraMove: "slow frontal push-in", speed: "slow" },
        }),
        stage("diagonal-approach", 2, "Aproximacion diagonal", "Mostrar profundidad y volumen.", {
          mustKeep: ["facade identity", "materials", "openings", "scale"],
          basePrompt: "Create a plausible diagonal exterior approach view from the same project.",
          editInstructions: "Keep the building identity, roofline, facade rhythm and materials.",
          stageDeltaInstructions: "Reveal depth and volume without redesigning the project.",
          motionPrompt: "slow diagonal dolly",
          clipMotion: { cameraMove: "slow diagonal dolly", speed: "slow" },
        }),
        stage("context-low", 3, "Contexto bajo", "Mostrar acceso, calle, parqueo o jardin si existe.", {
          mayAdd: ["subtle existing landscape enhancement", "plausible clean street if visible"],
          mustNotShow: ["unrelated urban context", "traffic unless cars enabled"],
          basePrompt: "Create a low exterior context view showing access, street, parking or garden only if plausible.",
          editInstructions: "Preserve immediate context and do not invent unrelated surroundings.",
          stageDeltaInstructions: "Lower camera slightly and emphasize entry/context.",
          motionPrompt: "low drone slide",
          clipMotion: { cameraMove: "low drone slide", speed: "slow" },
        }),
        stage("low-aerial", 4, "Dron bajo", "Preparar elevacion.", {
          mustKeep: ["footprint", "roofline", "facade geometry"],
          basePrompt: "Create a low aerial exterior view that begins to reveal roof and site.",
          editInstructions: "Respect footprint, roofline, facade and existing context.",
          stageDeltaInstructions: "Raise camera carefully; no impossible roof invention.",
          motionPrompt: "slow drone rise",
          clipMotion: { cameraMove: "slow drone rise", speed: "slow" },
        }),
        stage("final-aerial", 5, "Aerea final", "Cierre semi-aereo.", {
          mustKeep: ["project identity", "site logic", "scale", "roof and facade"],
          basePrompt: "Create a final semi-aerial hero reveal, cinematic and photorealistic.",
          editInstructions: "Preserve scale, architecture and site logic.",
          stageDeltaInstructions: "End with a polished aerial reveal.",
          motionPrompt: "gentle aerial reveal",
          clipMotion: { cameraMove: "gentle aerial reveal", speed: "slow" },
        }),
      ],
      clipStrategy: { motionStyle: "premium real estate drone movement" },
      forbiddenChanges: fidelityForbidden,
      templateWarnings: ["Tour de dron requiere exterior visible."],
    }),

    createVideoTemplate({
      id: "grey-shell-construction",
      name: "Obra gris a terminado",
      shortName: "Obra gris",
      description: "Evolucion desde espacio crudo/obra gris hasta resultado final.",
      category: "construction",
      purpose: "Mostrar evolucion desde espacio crudo/obra gris hasta resultado final.",
      bestFor: ["locales comerciales", "remodelaciones", "interiores", "restaurantes", "oficinas", "habitaciones"],
      notFor: ["vistas donde no se entiende la estructura base"],
      requiredInputs: ["image", "render", "reference"],
      optionalInputs: ["plan", "material_reference"],
      minimumRecommendedInputs: 1,
      supportsHumans: true,
      supportsCars: false,
      defaultCameraMotion: "locked construction transformation",
      analysisFocus: ["structure", "walls", "floor", "ceiling", "doors", "windows", "columns", "final finishes", "furniture", "lighting", "removable objects"],
      readinessChecks: ["allow removal of furniture/finishes only in early stages"],
      baseImageOutputs: [
        stage("raw-shell", 1, "Obra gris inicial", "Mostrar la misma arquitectura en estado crudo.", {
          mayRemove: ["final furniture", "decoration", "finishes", "textiles", "movable objects"],
          mayAdd: ["concrete", "raw plaster", "unfinished floor", "unfinished surfaces"],
          mustKeep: ["geometry", "walls", "openings", "camera", "proportions"],
          basePrompt: "Create a raw grey-shell construction state of the exact same architectural space.",
          editInstructions: "Remove final movable furniture and styling only. Preserve geometry, walls, openings, floor base and camera.",
          stageDeltaInstructions: "Show raw concrete/plaster, unfinished floor and construction-ready surfaces.",
          motionPrompt: "slow empty construction walkthrough",
          clipMotion: { cameraMove: "slow empty construction walkthrough", speed: "slow" },
        }),
        stage("prepared-structure", 2, "Estructura preparada", "Mostrar estructura limpia antes de acabados.", {
          mayAdd: ["prepared walls", "base floor", "subtle conduits", "ready surfaces"],
          mustNotShow: ["final furniture", "final decoration", "final style"],
          basePrompt: "Create a clean prepared structure stage before finishes.",
          editInstructions: "Keep exact architecture. Show prepared walls/floor and subtle construction preparation.",
          stageDeltaInstructions: "Transition from raw shell to clean ready structure.",
          motionPrompt: "steady forward reveal",
          clipMotion: { cameraMove: "steady forward reveal", speed: "slow" },
        }),
        stage("main-finishes", 3, "Acabados principales", "Mostrar instalacion de piso, paredes, cielo e iluminacion base.", {
          mayAdd: ["main materials", "flooring", "paint", "base lighting"],
          basePrompt: "Create a mid-construction stage with main finishes installed.",
          editInstructions: "Introduce floor, wall, ceiling and base lighting finishes while preserving layout.",
          stageDeltaInstructions: "Materials appear clearly, but no final decoration overload.",
          motionPrompt: "soft material reveal",
          clipMotion: { cameraMove: "soft material reveal", speed: "slow" },
        }),
        stage("fitout-furniture", 4, "Equipamiento y mobiliario", "Agregar mobiliario y piezas funcionales.", {
          mayAdd: ["large detected objects", "medium detected objects", "functional furniture"],
          mustNotShow: ["excessive final decoration"],
          basePrompt: "Create an advanced fit-out stage with functional furniture and equipment.",
          editInstructions: "Add large and medium objects detected in the inventory without changing architecture.",
          stageDeltaInstructions: "Furniture appears progressively; final small decor is still restrained.",
          motionPrompt: "dolly-in with subtle transformation",
          clipMotion: { cameraMove: "dolly-in with subtle transformation", speed: "slow" },
        }),
        stage("final-completed", 5, "Resultado final", "Hero final completo.", {
          mayAdd: ["realism", "light", "texture", "atmosphere"],
          mustKeep: ["final design", "objects", "materials", "composition"],
          basePrompt: "Create the final completed photorealistic architectural hero image.",
          editInstructions: "Preserve final design, object placement, materials and camera. Improve realism only.",
          stageDeltaInstructions: "Show finished, polished, client-ready result.",
          motionPrompt: "hero cinematic push-in",
          clipMotion: { cameraMove: "hero cinematic push-in", speed: "slow" },
        }),
      ],
      clipStrategy: { motionStyle: "locked transformation from construction to finished space" },
      forbiddenChanges: fidelityForbidden,
    }),

    createVideoTemplate({
      id: "progressive-decoration",
      name: "Decoracion progresiva",
      shortName: "Decoracion",
      description: "Espacio decorado por capas, desde vacio hasta resultado final.",
      category: "interior",
      purpose: "Mostrar como un espacio se decora por capas, desde vacio hasta resultado final.",
      bestFor: ["habitaciones", "salas", "apartamentos", "restaurantes", "oficinas", "interiores"],
      notFor: ["fachadas exteriores sin interior visible"],
      requiredInputs: ["image", "render", "reference"],
      optionalInputs: ["material_reference", "furniture_reference"],
      minimumRecommendedInputs: 1,
      supportsHumans: true,
      supportsCars: false,
      defaultCameraMotion: "slow interior reveal",
      analysisFocus: ["room geometry", "movable objects", "furniture", "decor", "textiles", "lighting", "materials"],
      readinessChecks: ["each stage must add a clear layer", "avoid repeated final images"],
      baseImageOutputs: [
        stage("empty-space", 1, "Espacio vacio", "Mantener arquitectura y retirar objetos movibles/decoracion.", {
          mayRemove: ["decor", "small objects", "textiles", "accessories", "movable furniture"],
          mustKeep: ["walls", "doors", "windows", "floor", "ceiling", "camera", "geometry"],
          mayAdd: ["realism only"],
          basePrompt: "Create the same interior space empty and clean, preserving exact architecture.",
          editInstructions: "Remove movable decor and styling. Do not change walls, doors, windows, floor, ceiling or camera.",
          stageDeltaInstructions: "No furniture layer yet; only a realistic empty base.",
          motionPrompt: "slow clean empty room reveal",
          clipMotion: { cameraMove: "slow clean empty room reveal", speed: "slow" },
        }),
        stage("large-objects", 2, "Objetos grandes", "Introducir mobiliario principal.", {
          mayAdd: ["bed", "sofa", "table", "wardrobe", "main furniture"],
          mustNotShow: ["small decor", "accessories", "excessive styling"],
          basePrompt: "Add only the primary large furniture pieces to the same interior.",
          editInstructions: "Use largeObjects and furniture from the visual inventory. Keep architecture and camera locked.",
          stageDeltaInstructions: "Add one clear layer: large furniture only.",
          motionPrompt: "subtle furniture reveal",
          clipMotion: { cameraMove: "subtle furniture reveal", speed: "slow" },
        }),
        stage("medium-objects", 3, "Objetos medianos", "Introducir objetos funcionales medianos.", {
          mayAdd: ["chairs", "lamps", "side tables", "rugs", "curtains", "shelves"],
          mustNotShow: ["changed large objects"],
          basePrompt: "Add medium functional objects, textiles and lighting to the existing furniture layout.",
          editInstructions: "Do not move or redesign large objects. Add medium layer only.",
          stageDeltaInstructions: "Increase completeness with medium objects and textiles.",
          motionPrompt: "soft lateral movement",
          clipMotion: { cameraMove: "soft lateral movement", speed: "slow" },
        }),
        stage("small-decor", 4, "Objetos pequenos y decoracion", "Agregar decoracion fina.", {
          mayAdd: ["art", "books", "vases", "plants", "cushions", "accessories"],
          mustNotShow: ["changed layout", "changed large or medium objects"],
          basePrompt: "Add small decor and fine styling while preserving all established furniture.",
          editInstructions: "Use smallObjects and decorObjects from inventory. Do not change layout.",
          stageDeltaInstructions: "Add final decorative layer, not new architecture.",
          motionPrompt: "detail-rich cinematic drift",
          clipMotion: { cameraMove: "detail-rich cinematic drift", speed: "slow" },
        }),
        stage("final-style-lighting", 5, "Estilo y luces finales", "Final hero con luz y estilo.", {
          mayAdd: ["better light", "atmosphere", "textures", "photographic finish"],
          mustNotShow: ["moved objects", "unrequested style change"],
          basePrompt: "Create the final hero interior image with refined lighting, materials and photographic finish.",
          editInstructions: "Preserve all established objects, architecture and style. Improve realism only.",
          stageDeltaInstructions: "Final lighting and finish pass.",
          motionPrompt: "hero final push-in with warm light",
          clipMotion: { cameraMove: "hero final push-in with warm light", speed: "slow" },
        }),
      ],
      clipStrategy: { motionStyle: "layer-by-layer interior decoration reveal" },
      forbiddenChanges: fidelityForbidden,
    }),

    createVideoTemplate({
      id: "front-to-aerial",
      name: "Frontal a aerea",
      shortName: "Frontal-aerea",
      description: "Eleva de vista frontal a semi-aerea.",
      category: "exterior",
      purpose: "Elevar de vista frontal a semi-aerea.",
      bestFor: ["fachadas", "casas", "locales", "edificios bajos"],
      notFor: ["interiores", "fachadas sin contexto"],
      requiredInputs: ["image", "render", "reference"],
      optionalInputs: ["site_plan", "roof_reference"],
      minimumRecommendedInputs: 1,
      supportsHumans: true,
      supportsCars: true,
      defaultCameraMotion: "vertical crane rise / drone rise",
      analysisFocus: ["facade", "roof visibility", "site context", "front composition"],
      readinessChecks: ["warn if roof is not visible", "do not invent full lot", "do not add floors"],
      templateWarnings: ["Si no se ve techo, la vista aerea sera aproximada."],
      baseImageOutputs: [
        stage("front-exact", 1, "Vista frontal exacta", "Vista frontal fiel y clara.", {
          basePrompt: "Create the exact frontal exterior view, photorealistic and faithful.",
          editInstructions: "Preserve facade, materials, signage, openings and context.",
          stageDeltaInstructions: "No elevation yet. This anchors the sequence.",
          motionPrompt: "locked frontal hold",
          clipMotion: { cameraMove: "subtle frontal hold", speed: "slow" },
        }),
        stage("raised-front", 2, "Frontal elevada", "Misma fachada con camara mas alta.", {
          basePrompt: "Raise the frontal camera slightly while preserving facade geometry.",
          editInstructions: "Do not add floors or redesign roof. Keep front identity.",
          stageDeltaInstructions: "Crane up gently from the exact front.",
          motionPrompt: "vertical crane rise",
          clipMotion: { cameraMove: "vertical crane rise", speed: "slow" },
        }),
        stage("high-diagonal", 3, "Diagonal elevada", "Angulo diagonal alto plausible.", {
          basePrompt: "Create a high diagonal exterior view, plausible from the frontal reference.",
          editInstructions: "Preserve facade, footprint and material identity.",
          stageDeltaInstructions: "Transition from frontal to elevated diagonal.",
          motionPrompt: "high diagonal drone slide",
          clipMotion: { cameraMove: "high diagonal drone slide", speed: "slow" },
        }),
        stage("soft-aerial", 4, "Semi-aerea final", "Cierre semi-aereo sobrio.", {
          basePrompt: "Create a soft semi-aerial final reveal of the same building.",
          editInstructions: "Do not invent full lot. Respect roof and facade logic.",
          stageDeltaInstructions: "End with controlled aerial perspective.",
          motionPrompt: "soft aerial reveal",
          clipMotion: { cameraMove: "soft aerial reveal", speed: "slow" },
        }),
      ],
      clipStrategy: { motionStyle: "controlled crane/drone rise" },
      forbiddenChanges: fidelityForbidden,
    }),

    createVideoTemplate({
      id: "simple-360",
      name: "Vista 360 sencilla",
      shortName: "360 simple",
      description: "Orbita simple alrededor de objeto, fachada, stand o local pequeno.",
      category: "architecture",
      purpose: "Simular una rotacion simple alrededor del sujeto arquitectonico.",
      bestFor: ["objeto", "fachada", "stand", "local pequeno", "mobiliario"],
      notFor: ["espacios complejos sin laterales visibles"],
      requiredInputs: ["image", "render", "reference"],
      optionalInputs: ["side_reference", "plan"],
      minimumRecommendedInputs: 1,
      singleImagePolicy: "allowed_with_creative_side_warning",
      supportsHumans: false,
      supportsCars: true,
      defaultCameraMotion: "subtle orbit",
      analysisFocus: ["object identity", "materials", "front view", "possible sides"],
      readinessChecks: ["warn if only one image", "do not invent complex sides"],
      templateWarnings: ["Con una sola imagen, las vistas laterales seran una aproximacion creativa."],
      baseImageOutputs: [
        stage("front", 1, "Frente", "Vista frontal inicial.", { basePrompt: "Create the front view exactly.", editInstructions: "Preserve front composition, scale and materials.", stageDeltaInstructions: "Orbit starts at front.", motionPrompt: "front hold", clipMotion: { cameraMove: "subtle front hold", speed: "slow" } }),
        stage("left-diagonal", 2, "Diagonal izquierda", "Rotacion leve hacia izquierda.", { basePrompt: "Create a plausible left diagonal view.", editInstructions: "Maintain same identity and materials.", stageDeltaInstructions: "Rotate left gently.", motionPrompt: "subtle orbit left", clipMotion: { cameraMove: "subtle orbit left", speed: "slow" } }),
        stage("side", 3, "Lateral", "Vista lateral controlada.", { basePrompt: "Create a controlled side view only as far as plausible from references.", editInstructions: "Do not invent complex hidden sides.", stageDeltaInstructions: "Show side approximation with honesty.", motionPrompt: "side orbit pass", clipMotion: { cameraMove: "side orbit pass", speed: "slow" } }),
        stage("right-diagonal", 4, "Diagonal derecha", "Rotacion leve hacia derecha.", { basePrompt: "Create a plausible right diagonal view.", editInstructions: "Keep design, scale and materials consistent.", stageDeltaInstructions: "Rotate back toward front.", motionPrompt: "subtle orbit right", clipMotion: { cameraMove: "subtle orbit right", speed: "slow" } }),
        stage("front-final", 5, "Frente final", "Frente final pulido.", { basePrompt: "Return to the front hero view with photoreal finish.", editInstructions: "Do not alter signage or identity.", stageDeltaInstructions: "Close the orbit at front.", motionPrompt: "front final push-in", clipMotion: { cameraMove: "front final push-in", speed: "slow" } }),
      ],
      clipStrategy: { motionStyle: "subtle orbit with identity lock" },
      forbiddenChanges: fidelityForbidden,
    }),

    createVideoTemplate({
      id: "architectural-walkthrough",
      name: "Recorrido arquitectonico",
      shortName: "Recorrido",
      description: "Recorrido interior o exterior tipo walkthrough.",
      category: "interior/exterior",
      purpose: "Crear un recorrido arquitectonico controlado sin inventar habitaciones.",
      bestFor: ["interiores", "restaurantes", "hoteles", "casas", "oficinas", "locales"],
      notFor: ["una sola foto que no permite continuidad amplia"],
      requiredInputs: ["image", "render", "reference"],
      optionalInputs: ["plan", "sequence_reference"],
      minimumRecommendedInputs: 1,
      supportsHumans: true,
      supportsCars: true,
      defaultCameraMotion: "slow dolly forward",
      analysisFocus: ["entrance", "main area", "path continuity", "materials", "objects", "plan if available"],
      readinessChecks: ["if one photo, keep recorrido corto y controlado", "if plan exists, use it for continuity"],
      baseImageOutputs: [
        stage("entrance", 1, "Entrada", "Inicio del recorrido.", { basePrompt: "Create the entrance or first controlled viewpoint.", editInstructions: "Preserve layout, materials and objects.", stageDeltaInstructions: "Open with the most plausible entrance view.", motionPrompt: "slow dolly forward", clipMotion: { cameraMove: "slow dolly forward", speed: "slow" } }),
        stage("first-advance", 2, "Primer avance", "Primer avance hacia el espacio.", { basePrompt: "Create the first forward movement stage.", editInstructions: "Do not invent rooms. Keep continuity.", stageDeltaInstructions: "Move forward slightly.", motionPrompt: "steady forward dolly", clipMotion: { cameraMove: "steady forward dolly", speed: "slow" } }),
        stage("main-area", 3, "Area principal", "Area principal del recorrido.", { basePrompt: "Create the main area viewpoint.", editInstructions: "Preserve main layout, materials and furniture.", stageDeltaInstructions: "Reveal principal space.", motionPrompt: "main area reveal", clipMotion: { cameraMove: "main area reveal", speed: "slow" } }),
        stage("architectural-detail", 4, "Detalle arquitectonico", "Detalle de material o elemento arquitectonico.", { basePrompt: "Create a detail-rich architectural view.", editInstructions: "Emphasize a real material or feature from inventory.", stageDeltaInstructions: "Focus on detail without breaking continuity.", motionPrompt: "detail drift", clipMotion: { cameraMove: "detail drift", speed: "slow" } }),
        stage("hero-closing", 5, "Cierre hero", "Cierre hero cinematografico.", { basePrompt: "Create a final hero closing view.", editInstructions: "Preserve materials, layout and objects.", stageDeltaInstructions: "End with a polished hero frame.", motionPrompt: "hero closing push-in", clipMotion: { cameraMove: "hero closing push-in", speed: "slow" } }),
      ],
      clipStrategy: { motionStyle: "slow architectural dolly forward" },
      forbiddenChanges: fidelityForbidden,
    }),

    createVideoTemplate({
      id: "cad-to-realistic",
      name: "De plano a realista",
      shortName: "Plano-realista",
      description: "De DXF/DWG/PDF de planos a visualizacion realista.",
      category: "technical",
      purpose: "Convertir planos o referencias tecnicas en narrativa visual que termina en render realista.",
      bestFor: ["DXF", "DWG convertido", "PDF de planos", "planta arquitectonica", "layouts"],
      notFor: ["imagenes sin lectura de layout"],
      requiredInputs: ["dxf", "dwg", "pdf", "plan"],
      optionalInputs: ["style_reference", "material_reference"],
      minimumRecommendedInputs: 1,
      supportsHumans: false,
      supportsCars: false,
      defaultCameraMotion: "blueprint to volume reveal",
      analysisFocus: ["walls", "doors", "windows", "labels", "circulation", "room layout", "style references"],
      readinessChecks: ["warn if no style/material references", "preserve labels if applicable"],
      templateWarnings: ["No hay referencias de estilo/materiales: el resultado final sera inferido."],
      baseImageOutputs: [
        stage("clean-technical-plan", 1, "Plano tecnico limpio", "Plano tecnico limpio.", { basePrompt: "Clean and clarify the technical plan.", editInstructions: "Preserve walls, openings, proportions and labels.", stageDeltaInstructions: "Make plan legible without changing layout.", motionPrompt: "technical plan hold", clipMotion: { cameraMove: "technical plan hold", speed: "slow" } }),
        stage("highlighted-plan", 2, "Plano resaltado", "Plano con zonas resaltadas.", { basePrompt: "Highlight circulation and important zones on the same plan.", editInstructions: "Do not move walls, doors or windows.", stageDeltaInstructions: "Add visual emphasis only.", motionPrompt: "blueprint highlight reveal", clipMotion: { cameraMove: "blueprint highlight reveal", speed: "slow" } }),
        stage("basic-volume", 3, "Volumen basico", "Volumen basico desde el plano.", { basePrompt: "Translate the plan into basic architectural volume.", editInstructions: "Respect layout, openings and proportions.", stageDeltaInstructions: "Extrude plan into simple volume.", motionPrompt: "plan to volume reveal", clipMotion: { cameraMove: "plan to volume reveal", speed: "slow" } }),
        stage("semi-realistic", 4, "Visualizacion semirrealista", "Visualizacion semirrealista.", { basePrompt: "Develop a semi-realistic visualization from the same layout.", editInstructions: "Preserve distribution and openings.", stageDeltaInstructions: "Add materials and depth carefully.", motionPrompt: "semi-realistic reveal", clipMotion: { cameraMove: "semi-realistic reveal", speed: "slow" } }),
        stage("final-render", 5, "Render final", "Render final realista.", { basePrompt: "Create the final photorealistic render from the technical layout.", editInstructions: "Do not invent rooms or move doors/windows. Use style references if available.", stageDeltaInstructions: "Final photoreal finish.", motionPrompt: "blueprint to photoreal final", clipMotion: { cameraMove: "blueprint to photoreal final", speed: "slow" } }),
      ],
      clipStrategy: { motionStyle: "blueprint to photoreal reveal" },
      forbiddenChanges: fidelityForbidden,
    }),

    createVideoTemplate({
      id: "before-after",
      name: "Antes y despues",
      shortName: "Antes-despues",
      description: "Transformacion directa entre estado actual y propuesta final.",
      category: "transformation",
      purpose: "Mostrar transformacion directa entre estado actual y propuesta final.",
      bestFor: ["remodelaciones", "habitaciones", "locales", "fachadas", "interiores"],
      notFor: ["cambios estructurales no autorizados"],
      requiredInputs: ["image", "reference"],
      optionalInputs: ["proposal_reference", "material_reference"],
      minimumRecommendedInputs: 1,
      supportsHumans: true,
      supportsCars: true,
      defaultCameraMotion: "before-to-after transformation",
      analysisFocus: ["current state", "clutter", "requested intervention", "structure to preserve"],
      readinessChecks: ["current state must preserve input", "no structural change without permission"],
      baseImageOutputs: [
        stage("current-state", 1, "Estado actual", "Estado actual preservado.", { basePrompt: "Preserve the current state exactly, with only photo cleanup.", editInstructions: "Do not change structure or design.", stageDeltaInstructions: "Baseline before frame.", motionPrompt: "before hold", clipMotion: { cameraMove: "before hold", speed: "slow" } }),
        stage("cleaned-base", 2, "Limpieza visual", "Limpieza visual controlada.", { mayRemove: ["clutter", "specified removable items"], basePrompt: "Clean visual clutter only while preserving architecture.", editInstructions: "Remove only clutter or user-indicated elements.", stageDeltaInstructions: "Clean base before intervention.", motionPrompt: "cleaning transformation", clipMotion: { cameraMove: "cleaning transformation", speed: "slow" } }),
        stage("main-intervention", 3, "Intervencion principal", "Intervencion principal solicitada.", { mayAdd: ["requested changes"], basePrompt: "Apply the main requested design intervention.", editInstructions: "Do not change structure unless explicitly requested.", stageDeltaInstructions: "Show primary before/after change.", motionPrompt: "main transformation reveal", clipMotion: { cameraMove: "main transformation reveal", speed: "slow" } }),
        stage("advanced-proposal", 4, "Propuesta avanzada", "Propuesta avanzada refinada.", { basePrompt: "Refine the proposal with materials, lighting and realism.", editInstructions: "Keep the main intervention and structure stable.", stageDeltaInstructions: "Advance materials and composition.", motionPrompt: "advanced proposal drift", clipMotion: { cameraMove: "advanced proposal drift", speed: "slow" } }),
        stage("final-after", 5, "Despues final", "Hero final realista.", { basePrompt: "Create the final after hero, photorealistic and client-ready.", editInstructions: "Preserve approved proposal and architecture.", stageDeltaInstructions: "Final after frame.", motionPrompt: "after hero push-in", clipMotion: { cameraMove: "after hero push-in", speed: "slow" } }),
      ],
      clipStrategy: { motionStyle: "controlled before-after transformation" },
      forbiddenChanges: fidelityForbidden,
    }),

    createVideoTemplate({
      id: "day-to-night",
      name: "Dia a noche",
      shortName: "Dia-noche",
      description: "El mismo proyecto cambia iluminacion durante el dia.",
      category: "lighting",
      purpose: "Mostrar el mismo proyecto cambiando iluminacion durante el dia.",
      bestFor: ["exteriores", "interiores con ventanas", "fachadas", "hoteles", "restaurantes"],
      notFor: ["espacios sin control de luz visible"],
      requiredInputs: ["image", "render", "reference"],
      optionalInputs: ["lighting_reference"],
      minimumRecommendedInputs: 1,
      supportsHumans: true,
      supportsCars: true,
      defaultCameraMotion: "time-lapse lighting transition",
      analysisFocus: ["lighting", "windows", "sky", "materials", "object stability"],
      readinessChecks: ["only lighting, sky, temperature and atmosphere change"],
      baseImageOutputs: [
        stage("clear-day", 1, "Dia claro", "Dia claro.", { basePrompt: "Create clear daylight version of the same project.", editInstructions: "Change only lighting/sky; keep all objects and design.", stageDeltaInstructions: "Daylight baseline.", motionPrompt: "daylight hold", clipMotion: { cameraMove: "daylight hold", speed: "slow" } }),
        stage("golden-hour", 2, "Golden hour", "Golden hour.", { basePrompt: "Create golden hour version of the same project.", editInstructions: "Change only warm light, sky and mood.", stageDeltaInstructions: "Warm sun angle appears.", motionPrompt: "golden hour light shift", clipMotion: { cameraMove: "golden hour light shift", speed: "slow" } }),
        stage("sunset", 3, "Atardecer", "Atardecer.", { basePrompt: "Create sunset version of the same project.", editInstructions: "No object/design changes.", stageDeltaInstructions: "Sky and color temperature move toward sunset.", motionPrompt: "sunset transition", clipMotion: { cameraMove: "sunset transition", speed: "slow" } }),
        stage("evening-lights", 4, "Noche con luces", "Noche con luces.", { basePrompt: "Create evening version with architectural lights active.", editInstructions: "Keep materials and objects. Activate plausible lights only.", stageDeltaInstructions: "Evening lighting appears.", motionPrompt: "evening light reveal", clipMotion: { cameraMove: "evening light reveal", speed: "slow" } }),
        stage("night-hero", 5, "Hero nocturno", "Hero nocturno.", { basePrompt: "Create final night hero with realistic architectural lighting.", editInstructions: "Do not change design or objects.", stageDeltaInstructions: "Final night atmosphere.", motionPrompt: "night hero push-in", clipMotion: { cameraMove: "night hero push-in", speed: "slow" } }),
      ],
      clipStrategy: { motionStyle: "stable time-lapse lighting transition" },
      forbiddenChanges: fidelityForbidden,
    }),

    createVideoTemplate({
      id: "progressive-materiality",
      name: "Materialidad progresiva",
      shortName: "Materialidad",
      description: "El proyecto gana materiales y texturas por etapas.",
      category: "materials",
      purpose: "Mostrar como el proyecto gana materiales y texturas.",
      bestFor: ["renders base", "modelos 3D simples", "SketchUp", "interiores", "fachadas"],
      notFor: ["proyectos donde la geometria aun debe cambiar"],
      requiredInputs: ["image", "render", "reference"],
      optionalInputs: ["material_reference"],
      minimumRecommendedInputs: 1,
      supportsHumans: false,
      supportsCars: false,
      defaultCameraMotion: "material reveal",
      analysisFocus: ["geometry", "floor", "walls", "furniture finishes", "textures", "materials"],
      readinessChecks: ["each stage adds materiality", "no geometry change"],
      baseImageOutputs: [
        stage("neutral-volume", 1, "Volumen neutro", "Volumen neutro.", { basePrompt: "Create the same project as neutral clean volume.", editInstructions: "Keep geometry and camera; simplify material expression.", stageDeltaInstructions: "Neutral base.", motionPrompt: "neutral volume reveal", clipMotion: { cameraMove: "neutral volume reveal", speed: "slow" } }),
        stage("floor-material", 2, "Piso", "Agregar piso.", { mayAdd: ["floor material"], basePrompt: "Add realistic floor material only.", editInstructions: "Do not change geometry or objects.", stageDeltaInstructions: "Floor material appears.", motionPrompt: "floor material reveal", clipMotion: { cameraMove: "floor material reveal", speed: "slow" } }),
        stage("wall-materials", 3, "Paredes/materiales principales", "Agregar materiales principales.", { mayAdd: ["wall materials", "main finishes"], basePrompt: "Add wall and primary materials.", editInstructions: "Preserve camera and layout.", stageDeltaInstructions: "Main material identity appears.", motionPrompt: "wall material reveal", clipMotion: { cameraMove: "wall material reveal", speed: "slow" } }),
        stage("furniture-finishes", 4, "Mobiliario y acabados", "Mobiliario y acabados.", { mayAdd: ["furniture finishes", "fixture finishes"], basePrompt: "Add furniture and fixture finishes.", editInstructions: "Do not add unrelated decor.", stageDeltaInstructions: "Finishes gain realism.", motionPrompt: "finish reveal", clipMotion: { cameraMove: "finish reveal", speed: "slow" } }),
        stage("final-textures", 5, "Texturas finales", "Texturas finales.", { mayAdd: ["texture detail", "photographic material depth"], basePrompt: "Create final material-rich photoreal image.", editInstructions: "Enhance texture and realism only.", stageDeltaInstructions: "Final texture pass.", motionPrompt: "final texture push-in", clipMotion: { cameraMove: "final texture push-in", speed: "slow" } }),
      ],
      clipStrategy: { motionStyle: "progressive material reveal" },
      forbiddenChanges: fidelityForbidden,
    }),

    createVideoTemplate({
      id: "commercial-walkthrough",
      name: "Recorrido comercial / local abierto",
      shortName: "Comercial",
      description: "Recorrido vendedor para local comercial.",
      category: "commercial",
      purpose: "Mostrar local comercial de forma vendedora.",
      bestFor: ["restaurantes", "cafeterias", "tiendas", "recepcion", "hoteles", "stands"],
      notFor: ["espacios residenciales sin programa comercial"],
      requiredInputs: ["image", "render", "reference"],
      optionalInputs: ["brand_reference", "plan"],
      minimumRecommendedInputs: 1,
      supportsHumans: true,
      supportsCars: false,
      defaultCameraMotion: "commercial cinematic walkthrough",
      analysisFocus: ["facade/access", "signage", "layout", "service/product zone", "atmosphere", "people allowed"],
      readinessChecks: ["people only if enabled", "preserve signage", "do not invent brand"],
      baseImageOutputs: [
        stage("facade-access", 1, "Fachada o acceso", "Fachada o acceso.", { basePrompt: "Create commercial facade/access view.", editInstructions: "Preserve signage and brand identity; do not invent brand.", stageDeltaInstructions: "Open with access.", motionPrompt: "commercial access push-in", clipMotion: { cameraMove: "commercial access push-in", speed: "slow" } }),
        stage("entrance", 2, "Entrada", "Entrada.", { basePrompt: "Create entrance view into the commercial space.", editInstructions: "Maintain layout and signage.", stageDeltaInstructions: "Move inward.", motionPrompt: "entrance dolly", clipMotion: { cameraMove: "entrance dolly", speed: "slow" } }),
        stage("main-commercial-area", 3, "Area principal", "Area principal comercial.", { basePrompt: "Create main commercial area view.", editInstructions: "Preserve layout, furniture and service logic.", stageDeltaInstructions: "Reveal main sales/service area.", motionPrompt: "main commercial reveal", clipMotion: { cameraMove: "main commercial reveal", speed: "slow" } }),
        stage("product-service-zone", 4, "Barra, producto o servicio", "Zona de producto/servicio.", { basePrompt: "Create product or service zone detail.", editInstructions: "Preserve brand and visible text.", stageDeltaInstructions: "Focus on functional commercial zone.", motionPrompt: "service zone drift", clipMotion: { cameraMove: "service zone drift", speed: "slow" } }),
        stage("atmosphere-with-life", 5, "Ambiente final", "Ambiente final.", { mayAdd: ["subtle people only if enabled"], basePrompt: "Create final commercial atmosphere view.", editInstructions: "Add people only if user enabled, subtle and not blocking architecture.", stageDeltaInstructions: "Final selling atmosphere.", motionPrompt: "commercial hero close", clipMotion: { cameraMove: "commercial hero close", speed: "slow" } }),
      ],
      clipStrategy: { motionStyle: "commercial cinematic walkthrough" },
      forbiddenChanges: fidelityForbidden,
    }),

    createVideoTemplate({
      id: "basic-render-to-photoreal",
      name: "Boceto/render basico a foto realista",
      shortName: "Foto real",
      description: "Convertir mockup, SketchUp, render pobre o imagen basica en fotografia realista.",
      category: "transformation",
      purpose: "Convertir mockup, SketchUp, render pobre o imagen basica en fotografia realista.",
      bestFor: ["SketchUp", "modelos simples", "renders basicos", "mockups", "conceptos"],
      notFor: ["cambios de diseno no aprobados"],
      requiredInputs: ["image", "render", "reference"],
      optionalInputs: ["material_reference", "lighting_reference"],
      minimumRecommendedInputs: 1,
      supportsHumans: false,
      supportsCars: false,
      defaultCameraMotion: "render-to-reality reveal",
      analysisFocus: ["geometry", "camera", "materials", "texts", "realism gaps"],
      readinessChecks: ["geometry never changes", "only materials, light, realism and quality improve"],
      baseImageOutputs: [
        stage("clean-reference", 1, "Referencia limpia", "Referencia limpia.", { basePrompt: "Clean the basic render/reference without changing geometry.", editInstructions: "Keep composition and all visible text.", stageDeltaInstructions: "Clean baseline.", motionPrompt: "clean reference hold", clipMotion: { cameraMove: "clean reference hold", speed: "slow" } }),
        stage("geometry-locked", 2, "Geometria bloqueada", "Geometria bloqueada.", { basePrompt: "Lock and clarify geometry of the exact same scene.", editInstructions: "No geometry changes; make edges and perspective credible.", stageDeltaInstructions: "Geometry becomes more credible, not different.", motionPrompt: "geometry lock reveal", clipMotion: { cameraMove: "geometry lock reveal", speed: "slow" } }),
        stage("realistic-materials", 3, "Materiales realistas", "Materiales realistas.", { mayAdd: ["realistic material behavior"], basePrompt: "Improve materials to realistic architectural quality.", editInstructions: "Keep material intent and object identity.", stageDeltaInstructions: "Materials gain realism.", motionPrompt: "material realism reveal", clipMotion: { cameraMove: "material realism reveal", speed: "slow" } }),
        stage("realistic-lighting", 4, "Iluminacion realista", "Iluminacion realista.", { mayAdd: ["realistic lighting", "shadows", "reflections"], basePrompt: "Improve lighting, shadows and reflections realistically.", editInstructions: "Do not add objects or alter composition.", stageDeltaInstructions: "Lighting becomes photographic.", motionPrompt: "lighting realism shift", clipMotion: { cameraMove: "lighting realism shift", speed: "slow" } }),
        stage("final-photograph", 5, "Foto final", "Foto final.", { basePrompt: "Create the final photorealistic architectural photograph.", editInstructions: "Preserve geometry, camera, objects and visible text.", stageDeltaInstructions: "Final photographic finish.", motionPrompt: "render-to-reality hero", clipMotion: { cameraMove: "render-to-reality hero", speed: "slow" } }),
      ],
      clipStrategy: { motionStyle: "render-to-reality reveal" },
      forbiddenChanges: fidelityForbidden,
    }),
  ];

  function getVideoTemplateById(templateId) {
    return templates.find((template) => template.id === templateId) || null;
  }

  function getVideoTemplateOptions() {
    return templates.map((template) => ({
      id: template.id,
      name: template.name,
      description: template.description,
      category: template.category,
    }));
  }

  function normalizeTemplateInputTypes(inputs) {
    return (inputs || []).map((input) => input.type || input.mimeType || "unknown");
  }

  function validateTemplateReadiness(template, inputs, analysis) {
    const warnings = [];
    const blockers = [];
    const safeInputs = inputs || [];
    if (!safeInputs.length) blockers.push("Debes seleccionar al menos un input.");
    if (template && safeInputs.length < template.minimumRecommendedInputs) warnings.push(`Esta plantilla recomienda al menos ${template.minimumRecommendedInputs} input(s).`);
    if (template?.id === "drone-tour" && analysis?.spaceType === "interior") blockers.push("Tour de dron es solo para exteriores. Usa Recorrido arquitectonico.");
    if (template?.id === "simple-360" && safeInputs.length === 1) warnings.push("Con una sola imagen, las vistas laterales seran una aproximacion creativa.");
    if (template?.id === "front-to-aerial" && !analysis?.architecture?.roof?.length) warnings.push("No se ve techo claramente; la vista aerea sera aproximada.");
    if (template?.id === "cad-to-realistic") {
      const hasStyleReference = safeInputs.some((input) => input.type === "reference" || input.metadata?.styleReference);
      if (!hasStyleReference) warnings.push("No hay referencias de estilo/materiales. El resultado final sera inferido.");
    }
    return { ok: blockers.length === 0, warnings, blockers };
  }

  window.VIDEO_TEMPLATES = templates;
  window.createVideoTemplate = createVideoTemplate;
  window.createBaseImageOutput = createBaseImageOutput;
  window.getVideoTemplateById = getVideoTemplateById;
  window.getVideoTemplateOptions = getVideoTemplateOptions;
  window.normalizeTemplateInputTypes = normalizeTemplateInputTypes;
  window.validateTemplateReadiness = validateTemplateReadiness;
})();
